#!/bin/bash
if test -z $1; then
exit 255
fi

mkdir -p -m 777 builds/$1
mkdir -p -m 777 builds/$1/build
mkdir -p -m 777 builds/$1/deps
mkdir -p -m 777 builds/$1/src

sudo -A -u droshbuilder -n ./run-build-core $1

